### PR TITLE
Add support to Transport TLS

### PR DESCRIPTION
**Pull request by pruivo**
Configure the new options added in ISPN-12617

### CODE REVIEW

**Comment by ryanemerson** [comment]
@pruivo Is this only required for the operator?

@rigazilla Is currently in the process of refactoring the operator so that the config is generated directly, i.e. without the config-generator.

Depending on when this feature is required, it might be worth just adding this functionality directly to the operator?

**Comment by pruivo** [comment]
@ryanemerson @rigazilla if it is ready for Infinispan 13.0.0.Final, I'm ok dropping this. 
So, this repository will be removed/archived?

**Comment by rigazilla** [comment]
> @ryanemerson @rigazilla if it is ready for Infinispan 13.0.0.Final, I'm ok dropping this.
> So, this repository will be removed/archived?

yes, the plan is to have it ready for 13 Final and archive the config gen on the image

**Comment by ryanemerson** [comment]
> So, this repository will be removed/archived?

Ideally yes.

We still need a user story for standalone image use upstream, however I think this should simply be an image that allows:

1. Basic usage with no custom configuration i.e.:

```
docker run -p 11222:11222 -e USER="Michael" -e PASS="Bluth" infinispan/server
```

2. Allows the user to provide their own custom `xml | json | yaml` server configuration.

The current yaml -> config mapping should die.

**Comment by pruivo** [comment]
great. I'm going to still use this code for my testing :)

**Pull request closed without merging**
