### PR TITLE
Add tunnel options to bridge (relay) cluster

### PR DESCRIPTION
**Pull request by pruivo**
* For Kubernetes, use the GossipRouter to tunnel all the requests.

We aren't using the GossipRouter tunnel yet but I would like to make it available in the image (so, if we change it, it only requires a new operator image)

Tunneling is disabled by default.

### CODE REVIEW

**Comment by ryanemerson** [comment]
@pruivo I prefer to keep the logic in the templates in this instance as the two stacks are very similar and it leads to more verbose logic in `ConfigGenerator.java` to achieve the same thing. I've added a commit with the changes, let me know what you think

**Comment by ryanemerson** [comment]
O and to invoke my inner @oraNod, can you add some instructions to the README ... "Docs or it didn't happen!" :slightly_smiling_face:

**Comment by pruivo** [comment]
second thought, I'll keep the option hidden for now. This is only required for Bela's idea [1] and it will be necessary to make a summary of the changes requires (the blog post is quite extensive IMO).
[1] https://belaban.blogspot.com/2019/12/spanning-jgroups-kubernetes-based.html

**Comment by ryanemerson** [comment]
I resolved the conflicts from your other PR locally and pushed: https://github.com/infinispan/infinispan-image-artifacts/compare/4724c8e3bc421be47619e712c49bac11cc083476...master

Thanks @pruivo

**Pull request closed without merging**
